from .web_sync_modal import open_sir_web_account_sync_modal
from .game_settings_modal import open_game_settings_modal
from .satellite_modal import open_satellite_modal
from .profile_creator_modal import open_create_profile_choice_modal
from .custom_ping_modal import open_custom_server_ping_modal
from .accounts_modal import open_accounts_manager_modal
